config/routes.rb
Rails.application.routes.draw do

  # 管理者認証
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }

  # 管理者機能
  namespace :admin do
    resources :users, only: [:show, :index, :update]
  end

  # ユーザー認証
  devise_for :users, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
  end

  # ユーザー機能
  scope module: :public do
    root 'homes#top'
    get 'home' => 'homes#home'
    get '/post/hashtag/:name' => 'posts#hashtag'
    get 'search' => 'searches#search'
    get 'users/unsubscribe' => 'users#unsubscribe', as: 'confirm_unsubscribe'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    put 'users/withdraw' => 'users#withdraw'
    resources :notifications, only: :index
    resources :users, only: [:show, :index, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
    	get 'followings' => 'relationships#followings', as: 'followings'
    	get 'followers' => 'relationships#followers', as: 'followers'
    	get :favorites, on: :member
    end
    resources :posts do
      resource  :likes, only: [:create, :destroy]
      resource  :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
  end
end

app/views/layouts/_flash-messages.html.erb
<% flash.each do |message_type, message| %>
  <div class='time-limit'>
    <%= content_tag(:div, message, class: message_type) %>
  </div>
<% end %>

app/views/layouts/_header-admin.htm.erb
<header class='header border-bottom bg-white'>
  <div class='header__box mx-auto px-3 border-bottom'>
    <!-- 左寄せ部分 -->
    <div class='header__title-box py-3'>
      <%= link_to root_path do %>
        <%= image_tag "/assets/logo-sm.png" %>
      <% end %>
    </div>

    <!-- 右寄せ部分 -->
    <div class='header__content-box py-3'>
      <%= link_to 'ユーザー一覧', admin_users_path, class: 'header__content' %>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'header__content' %>
    </div>
  </div>
</header>

app/views/layouts/_header-admin.html.erb
<header class='header border-bottom bg-white'>
  <div class='header__box mx-auto d-flex px-3'>
    <div class='header__title-box py-3'>
      <%= link_to admin_users_path do %>
        <img src="<%= asset_path "logo-sm.png" %>" />
      <% end %>
    </div>

    <div class='header__content-box py-3 ml-auto'>
      <%= link_to 'ユーザー一覧', admin_users_path, class: 'header__content' %>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'header__content' %>
    </div>
  </div>
</header>

app/views/layouts/_header-user.html.erb
<header class='header border-bottom bg-white'>
  <div class='header__box mx-auto d-flex px-3'>
    <!-- 左寄せ部分 -->
    <div class='header__title-box py-3'>
      <%= link_to root_path do %>
        <img src="<%= asset_path "logo-sm.png" %>" />
      <% end %>
    </div>

    <!-- 右寄せ部分 -->
    <div class='header__content-box py-3 ml-auto'>
      <%= link_to 'ホーム', home_path, class: 'header__content' %>
      <%= link_to '検索', posts_path, class: 'header__content' %>
      <%= link_to '通知', notifications_path, class: 'header__content' %>
      <%= link_to 'マイページ', user_path(current_user), class: 'header__content' %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__content' %>
    </div>

    <!--右寄せ部分 (画面幅が小さい時用のハンバーガーメニュー) -->
    <input id='header_checkbox' class='header__hamburger-checkbox' type='checkbox'>
    <label for='header_checkbox' class='header__hamburger-icon py-3 ml-auto'>
      <i class="fas fa-ellipsis-h header__icon"></i>
    </label>
    <!--コンテンツ-->
    <div class='header__hamburger-box'>
      <label for='header_checkbox' class='header__hamburger-close'><i class="fas fa-times"></i></label>
      <%= link_to 'ホーム', home_path, class: 'header__hamburger-content' %>
      <%= link_to '検索', posts_path, class: 'header__hamburger-content' %>
      <%= link_to '通知', notifications_path, class: 'header__hamburger-content' %>
      <%= link_to 'ブックマーク', favorites_user_path(current_user), class: 'header__hamburger-content' %>
      <%= link_to 'マイページ', user_path(current_user), class: 'header__hamburger-content' %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__hamburger-content' %>
    </div>
    <!--背景-->
    <label for='header_checkbox' class='header__hamburger-back'></label>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <div class="bg-light">
      <!--ヘッダー-->
      <% if admin_signed_in? %>
        <%= render 'layouts/header-admin' %>
      <% elsif user_signed_in? %>
        <%= render 'layouts/header-user' %>
      <% end %>

      <!--メイン-->
      <main><%= yield %></main>

      <!-- モーダルウィンドウ(新規投稿) -->
      <div id="new-post" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    </div>
  </body>
</html>